### ISSUE TITLE
Admin API?

### ISSUE THREAD

**Issue by wstrange** [cachapa/firedart#2]
Does this work on the server to provide access to the firestore admin API?

I'd like to use this in a Cloud Run container to invoke firestore admin functions.  Possible?

**Comment by whesse** [comment]
I use the https://pub.dev/packages/firebase_admin_interop package to access the Firebase admin apis from Cloud Functions, which I think support the same languages (node.js) as Cloud Run.

This goes through the node.js SDK rather than the REST api.  Firebase suggests preferring the language APIs over REST, because they say they will put more effort into documenting them and making them complete.

There is an issue on the other Dart Firebase packages (the browser -> js interop -> js firebase SDK and cloud functions -> node.js -> node.js SDK) that there should be a unified package with a single interface that works for all platforms, perhaps this package should subscribe to that issue: https://github.com/pulyaevskiy/firebase-admin-interop/issues/16

**Comment by cachapa** [comment]
Sorry, I had notifications disabled for this project and didn't notice the issue report.

The Firestore Admin API is out of scope for this project (at least for now).

**Comment by wstrange** [comment]
Adding a note here just in case this comes back in scope.

Looking at https://firebase.google.com/docs/firestore/reference/rpc, and https://firebase.google.com/docs/firestore/use-rest-api#working_with_firebase_id_tokens. 
 
It looks like the only difference between  "admin" calls and "firebase user" calls is the type of token provided to the RPC call (service account for admin, firebase token for user based calls). Which make me think this library might in fact be usable admin / server side - if it can pass the right token?  I may be off base here...

**Comment by cachapa** [comment]
You're probably right. If someone would do that work and it wouldn't be a major change I could see it being included in the project.

**Comment by wstrange** [comment]
I did a little hacking today, and indeed it is quite possible to use  the generated  grpc code to access the Admin API. It's the same API - you just need to supply service account credentials instead of user credentials.  

I have a gist here: https://gist.github.com/wstrange/52c33cfb3c768718af607737ef4345d4 

I'll see if I have time to clean this up a bit and try to integrate (but in the meantime if you want to run with the above feel free ;-) )

For my use cases, Admin access to Firestore is the an exciting feature since the client APIs are fairly well covered by Google. Being able to write cloud functions that access Firestore would be icing on the cake!

**Comment by cachapa** [comment]
Looks good! Unfortunately I don't have time work on this myself currently, but if you do it I'll gladly integrate it into the codebase.

I guess this means the admin API just became in-scope for this project. Reopening.

**Comment by giiyms** [comment]
Was the admin code ever merged?
