### ISSUE TITLE
Question in regards to email verification

### ISSUE THREAD

**Issue by MostHated** [cachapa/firedart#36]
Hey there,
    I have a question about email verification. Does a callback mechanism or stream of some sort exist similar to 'auth.signInState.listen' or 'ref.stream.listen' in which I can detect if/when a user verifies their email address when submitting their signup request? 

When I saw that there were some streams available within the package I was excited, as before I was just using all REST calls and I had the idea of, upon signup submission, having a "Please verify your email address to continue (or press cancel to return later)" screen in which I can have a listener for 'user.emailVerified'. Then once it changed, I could move them forward in my application right then and there as opposed to sending them back to the login and having them put in their credentials again after doing the verification. 

If not, is there any other way to go about it that I might not be thinking of, or do I just need to go the route I was before and just have them login again once they do get their email? I suppose I could try setting up some sort of timer to recheck every 5-10 seconds or similar.

(One last side question about streams, as I am somewhat new to them. When using something like ref.stream.listen, do I need to manually terminate these in the likely event that the user closes the application while still logged in, or anything like that?)

Thanks!
-MH

**Comment by cachapa** [comment]
Unfortunately there's no way to subscribe to changes to the email verification property. This is a limitation of the Firebase API, which the official SDKs also suffer from.

The way I've been solving this, is to create a screen in your app which requests the User object from the service and checks the isEmailVerified property. If it's false, you just show a message asking the user to verify their email and have a button below which triggers a new user refresh.
Once the property turns to true, you just navigate the user into your app.

I recommend caching the result of the checks to avoid that network request every time the user opens the app.

> One last side question about streams, as I am somewhat new to them. When using something like ref.stream.listen, do I need to manually terminate these in the likely event that the user closes the application while still logged in, or anything like that?

You should close every stream subscription when you're done using them. If you're using a StreamBuilder you don't need to worry about it, as it will be handled for you.
Otherwise you should catch the callback when your page is being dismissed and close the stream.

I strongly recommend using StreamBuilder though.

**Comment by MostHated** [comment]
Thanks for the detailed reply, I do appreciate it. I will have a go at what you described. Having an intermediary between the login and the user area with a simple button effectively saying "I have completed the verification", and then using that to reinitiate the check sounds like the next best thing. 

Considering the workflow already exists when you use 2FA on your own Google account and go to login somewhere new, your phone can pop up a screen in which you are able to simply press "Yes, this is me", and then the site you were trying to login to will then automatically move forward, it doesn't seem like it would be terribly difficult for them to allow this to work in a similar manner. 

I guess if I *really* wanted to do it, it could probably be done with a serverless function on the Firestore side. After this portion of my application is completed, there are a few functions I need to implement anyways and I can look more into it at that time.  This should certainly do the job until then.

As for the stream question, currently, I am using a mix of the service locator package [get_it](https://pub.dev/packages/get_it), [event](https://pub.dev/packages/event), and [provider](https://pub.dev/packages/provider) throughout my app. All of the authentication logic is in a ChangeNotifier class which gets initialized using MultiProvider, which calls an init() at the start of the app. 

After I asked my question yesterday I had added a dispose() as seen in the below excerpt:

```dart
 runApp(
    MultiProvider(providers: [
      ...
      ...
      ChangeNotifierProvider<FBAuthProvider>(create: (_) => FBAuthProvider()..init()),
    ], child: MyApp(app)),
  );
```

```dart
  @override
  void dispose() {
    ref.stream.listen((event) {}).cancel();
    auth.signInState.listen((event) {}).cancel();
    authStatus.valueChangedEvent.unsubscribeAll();
    super.dispose();
  }

  void init() async {
    authStatus.valueChangedEvent + (args) => this.status = authStatus.status;
    client = !kReleaseMode ? VerboseClient() : http.Client();
    hiveStore = await HiveStore.create();

    FirebaseAuth.initialize(data.getString('apiKey'), hiveStore);
    Firestore.initialize(data.getString('projectId'));

    auth = FirebaseAuth.instance;
    auth.httpClient = client;

    (auth.isSignedIn) ? silentLoginEvent() : log.i('Firebase instance created. Not logged in.');
    auth.signInState.listen((state) => statusChange(state));
  }
```

I am definitely not opposed to using a StreamBuilder, I am just not super familiar with it. In your opinion, being that what I have set up currently works (at least for creation and communication), does what I have cover proper disposal/cleanup of the stream, or is there still more to it that switching over to using a StreamBuilder would provide in addition to what I have implemented?

Thanks again, you have been quite helpful and I greatly appreciate it.
-MH

**Comment by cachapa** [comment]
If you're already using the Provider package then you can simply create a ChangeNotifier that wraps the stream and notifies listeners when something changes. For example:

``` dart
class AuthNotifier extends ChangeNotifier {
  final FirebaseAuth auth;
  AuthNotifier(this.auth) {
    auth.signInState.listen((isSignedIn) => notifyListeners());
  }
}
```

If you have a provider that you want to dispose, then you would unsubscribe from the stream on dispose, but for Auth you probably just want to instantiate it at app launch and keep it running until the app closes anyway.

BTW I'm closing this issue since it isn't an actual issue. Feel free to continue the conversation though.

**Comment by MostHated** [comment]
No worries at all about closing the issue. I just wasn't sure if closing the app without properly closing the stream might leave it open on a thread or something. I have come across that in other languages. I am still relatively new to dart/flutter, so just trying to make sure I am doing things the right way. 

You had mentioned "reloading" the user, which I just took as running ```User user = auth.getUser();``` again but then I saw an article that was using ```.getCurrentUser().reload()```. Does that exist somewhere in the package and I am just not seeing it? I looked in userGateway/authGateway but didn't see it. 

I ran into a small issue whereupon reloading the user by just calling getUser() again caused me to lose reference to user.email, which I was using to display the email in which the verification email was sent on the page for them to recheck their verification status, so I was caching the email to another field so that it could reload the user, but if there was a way to do it without that, that would be even better. If not, the small workaround doesn't seem like it is much of an issue.

Thanks,
-MH

**Comment by cachapa** [comment]
> I just wasn't sure if closing the app without properly closing the stream might leave it open on a thread or something.

What I mean by closing the app is completely stopping the process. This clears up anything that you had open, regardless of language or framework.

> You had mentioned "reloading" the user, which I just took as running `User user = auth.getUser();` again but then I saw an article that was using `.getCurrentUser().reload()`. Does that exist somewhere in the package and I am just not seeing it? I looked in userGateway/authGateway but didn't see it.

The official Firebase SDK caches the user, that's why they have the reload() method. Firedart does not do any caching so every call to getUser() hits the network.
