### ISSUE TITLE
Stream termination gRPC error

### ISSUE THREAD

**Issue by Kolis121** [cachapa/firedart#99]
Do we have a solution for the streaming termination on Desktop app?
Currently StreamBuilder will be disconnected randomly giving the following error crashing the whole application:

`flutter: Handling error gRPC Error (code: 16, codeName: UNAUTHENTICATED, message: Missing or invalid authentication., details: [], rawResponse: null, trailers: {content-disposition: attachment}) using FirestoreGateway._handleError`

**Comment by cachapa** [comment]
I believe this happens due to the access token expiring.

If that's the case, a workaround would be to catch that exception and reopen the stream (which should trigger a token refresh).

The fix would be to find a way to refresh the token using the gRPC API without having to terminate the connection.
Contributions here would be welcome :-)

**Comment by cachapa** [comment]
Closed by #130
